/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.glass.events.KeyEvent;
import comun.producto;
import static contapp_studio.principal.bloqueadas;
import static contapp_studio.principal.jTabbedPane1;
import static contapp_studio.principal.tk;
import controlador.conexion;
import controlador.operaciones;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static vista.inicio.superLocalID;

/**
 *
 * @author jairo
 */
public class factura extends javax.swing.JPanel implements ActionListener{
    private int egg=0;
    Connection con;
    operaciones op;
    conexion cn;
    private int registrado=0;
    private int idFactura=0;
    private int fila=0;
    private ArrayList<String> celda=new ArrayList<>(); 
    private ArrayList<Object> prodOrig=new ArrayList<>(); 
    private ArrayList<Object> eliminados=new ArrayList<>();
    
    /**
     * Creates new form factura
     * @param e
     */
    
    @Override
    public void actionPerformed(final ActionEvent e) {
        //tapPe.removeTap(title); --remover este panel
        this.removeAll();
        }
    
    
    public factura() {
        initComponents();
        btnRegistrar.setMnemonic(KeyEvent.VK_G);
        //*
        txtTel.setVisible(false);
        lblTel.setVisible(false);
        //
        txtNombre.setVisible(false);
        lblNombre.setVisible(false);
        //
        txtApellido.setVisible(false);
        lblApellido.setVisible(false);
        //
        txtFFin.setVisible(false);
        lblFFin.setVisible(false);
        //
        txtAbono.setVisible(false);
        lblAbono.setVisible(false);
        //*
        cn=new conexion();
        op=new operaciones();
        con=cn.AccederBD();
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantidad = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        chkSepare = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodList = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        lblAbono = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelar = new javax.swing.JButton();
        lblTotalDebe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPaga = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblFFin = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtFFin = new javax.swing.JFormattedTextField();
        txtVD = new javax.swing.JFormattedTextField();
        txtTotal = new javax.swing.JFormattedTextField();
        txtAbono = new javax.swing.JFormattedTextField();
        lblEstado = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(713, 426));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblCantidad.setText("Cantidades");
        lblCantidad.setEnabled(false);

        jSpinner1.setEnabled(false);
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinner1PropertyChange(evt);
            }
        });
        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
        });

        txtFecha.setEditable(false);
        txtFecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel6.setText("Fecha");

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Producto", "Producto", "Valor", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetalleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaDetalle);

        jLabel5.setText("ID Factura");

        txtID.setEditable(false);
        txtID.setText("auto");
        txtID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        chkSepare.setText("Separar");
        chkSepare.setNextFocusableComponent(prodList);
        chkSepare.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkSepareItemStateChanged(evt);
            }
        });
        chkSepare.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSepareStateChanged(evt);
            }
        });
        chkSepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSepareActionPerformed(evt);
            }
        });
        chkSepare.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chkSeparePropertyChange(evt);
            }
        });

        prodList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 7", "Item 8", "Item 9", "Item 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        prodList.setNextFocusableComponent(btnAgregar);
        prodList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                prodListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(prodList);

        btnAgregar.setText("+");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblAbono.setText("Abono");

        btnRegistrar.setText("Registrar");
        btnRegistrar.setEnabled(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        btnRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegistrarKeyPressed(evt);
            }
        });

        lblNombre.setText("Nombre");

        txtNombre.setNextFocusableComponent(lblApellido);

        lblTel.setText("Telefono");

        lblApellido.setText("Apellido");

        txtApellido.setNextFocusableComponent(txtTel);

        txtTel.setNextFocusableComponent(txtPaga);
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTotalDebe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTotalDebe.setText("TOTAL");
        lblTotalDebe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTotalDebeMouseClicked(evt);
            }
        });

        jLabel4.setText("PAGA");

        txtPaga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtPaga.setEnabled(false);
        txtPaga.setNextFocusableComponent(btnRegistrar);
        txtPaga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPagaFocusLost(evt);
            }
        });
        txtPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagaActionPerformed(evt);
            }
        });
        txtPaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagaKeyTyped(evt);
            }
        });

        jLabel7.setText("VUELTO");

        lblFFin.setText("Fecha fin");

        btnCalcular.setText("Calcular");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtFFin.setEditable(false);
        txtFFin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtFFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        txtVD.setEditable(false);
        txtVD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtVD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        txtTotal.setEditable(false);
        txtTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        txtAbono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        txtAbono.setNextFocusableComponent(txtNombre);
        txtAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAbonoKeyTyped(evt);
            }
        });

        lblEstado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblEstadoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblAbono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtID)
                                    .addComponent(txtAbono)))
                            .addComponent(chkSepare, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombre))
                            .addComponent(lblFFin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtTel)
                            .addComponent(txtFFin)))
                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblTotalDebe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32)
                                .addComponent(btnCalcular))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPaga, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalDebe)
                            .addComponent(btnCalcular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkSepare)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAbono)
                                    .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblFFin)
                                    .addComponent(txtFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblApellido)
                                        .addGap(29, 29, 29))
                                    .addComponent(lblTel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addComponent(txtTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jSeparator1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizar(){
        //* fecha
        Calendar hoy = Calendar.getInstance();
        SimpleDateFormat formatoPredefinido = new SimpleDateFormat("yyyy-MM-dd"); //("d/MM/yyyy hh:mm a");
        String presente=formatoPredefinido.format(hoy.getTime()).toString();
        txtFecha.setText(presente);
        //System.out.println("Presente: "+presente);
        //
        hoy.add(Calendar.DATE, 30);
        String futuro=(formatoPredefinido.format(hoy.getTime()).toString());
        txtFFin.setText(futuro);
        //* fecha
        //productos
        Object[][] dtUser;
        dtUser = op.select("productos", "id_producto, nombre, valor, existencias", "id_local=" + superLocalID, con);
        DefaultListModel modelo = new DefaultListModel();
        prodList.setModel(modelo);
        for(int i = 0; i<dtUser.length; i++){
            String id=dtUser[i][0].toString();
            String nomb=dtUser[i][1].toString();
            String val=dtUser[i][2].toString();
            String exis=dtUser[i][3].toString();
            if (eliminados.contains((Object) id)){
                System.out.println("Eliminado ID "+id+" Correspondiente a: "+nomb);
            }
            else{
                producto prod=new producto(id,nomb,val,exis);
                modelo.addElement(prod);
            }
        }
        prodList.setModel(modelo); 
        System.out.println("Actualizada ");
    }
    
    private void actualizaDetalle(){
        DefaultTableModel datos;
        Object[][] dtUser;
        String[] columNames = {"ID","Producto","Valor","Cantidad"};  
            dtUser = op.select("detalle", "id_producto, id_producto, valor, cantidad", "id_factura="+idFactura , con);
            datos = new DefaultTableModel(dtUser,columNames);                        
            tablaDetalle.setModel(datos);
            TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(datos);
            tablaDetalle.setRowSorter(elQueOrdena);
            //
            int total=0;
             for (int i=0;i<=fila; i++){
                 datos.setValueAt(celda.get(i), i, 1);
                 total=total+(Integer.parseInt((String) datos.getValueAt(i, 2))*Integer.parseInt((String) datos.getValueAt(i, 3)));
             }
        txtTotal.setText(Integer.toString(total));
        txtTotal.requestFocus();//
        txtPaga.requestFocus();//*  
    }
    
    private void prodListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_prodListValueChanged
        // TODO add your handling code here:
        if (prodList.isSelectionEmpty()==false){
            SpinnerModel sm;
            producto sel;
            sel = (producto) ((Object)prodList.getSelectedValue());
            int top = Integer.parseInt(sel.getExistencias());
            if (top>0){
                sm = new SpinnerNumberModel(1, 1, top, 1);//default value,lower bound,upper bound,increment by
                jSpinner1.setModel(sm);
                jSpinner1.setEnabled(true);
                lblCantidad.setEnabled(true); 
                btnAgregar.setEnabled(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No hay más existencias de éste producto");
                btnAgregar.setEnabled(false);
            } 
        }        
    }//GEN-LAST:event_prodListValueChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (registrado==0){
            //crear factura a la que se añadirá el detalle, y obtener el ID de la factura
            idFactura=op.insertar("factura", "fecha, id_local", "'"+txtFecha.getText()+"', " + superLocalID, con);
            txtID.setText(Integer.toString(idFactura));
            //BLOQUEAR
            int pesta=jTabbedPane1.getSelectedIndex();
            jTabbedPane1.setTitleAt(pesta, "Factura # "+idFactura);
            bloqueadas.add(jTabbedPane1.getSelectedComponent());
            registrado=1;
            //
            
        }
        jSpinner1.setEnabled(false);
        lblCantidad.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnRegistrar.setEnabled(true);
        btnCalcular.setEnabled(true);
        txtPaga.setEnabled(true);
        //
        //
        producto sel= (producto) (Object) prodList.getSelectedValue();
        int idProd = Integer.parseInt(sel.getId());
        int cantidad=Integer.parseInt(sel.getExistencias());
        int valor=Integer.parseInt(sel.getValor());
        //crear el array con los productos eliminados
        eliminados.add((Object) Integer.toString(idProd));
        prodOrig.add(new producto(Integer.toString(idProd),null,null,Integer.toString((Integer) jSpinner1.getValue())));//se agrega lo que se gastó en caso de cancelación para añadirlos
        //registrar detalle factura
        op.insertar("detalle", "id_factura,id_producto,cantidad,valor,id_local",Integer.parseInt(txtID.getText())+","+ idProd+","+(Integer)jSpinner1.getValue()+","+valor+","+ superLocalID, con);
        //modificar stock
        int stock=(cantidad-(Integer)jSpinner1.getValue());
        op.modificar("productos", "existencias ="+stock, "id_producto=" + idProd, con);
        //mostrar estado
        lblEstado.setText("Producto agregado");
        lblEstado.setForeground(new java.awt.Color(0,153,51));
        
        celda.add(fila, sel.getNombre());
        actualizaDetalle();
        actualizar();
        fila++;
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void chkSepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSepareActionPerformed
   
    }//GEN-LAST:event_chkSepareActionPerformed

    private void chkSepareStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSepareStateChanged

    }//GEN-LAST:event_chkSepareStateChanged

    private void chkSeparePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chkSeparePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSeparePropertyChange

    private void chkSepareItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkSepareItemStateChanged
        // TODO add your handling code here:
        if (chkSepare.isSelected()==false)
        {
            //*
            txtTel.setVisible(false);
            lblTel.setVisible(false);
            //
            txtNombre.setVisible(false);
            lblNombre.setVisible(false);
            //
            txtApellido.setVisible(false);
            lblApellido.setVisible(false);
            //
            txtFFin.setVisible(false);
            lblFFin.setVisible(false);
            //
            txtAbono.setVisible(false);
            lblAbono.setVisible(false);
            //
            lblTotalDebe.setText("TOTAL");
            //*
        }
        else
        {
            //*
            txtTel.setVisible(true);
            lblTel.setVisible(true);
            //
            txtNombre.setVisible(true);
            lblNombre.setVisible(true);
            //
            txtApellido.setVisible(true);
            lblApellido.setVisible(true);
            //
            txtFFin.setVisible(true);
            lblFFin.setVisible(true);
            //
            txtAbono.setVisible(true);
            lblAbono.setVisible(true);
            //
            lblTotalDebe.setText("DEBE");
            //*
        }
    }//GEN-LAST:event_chkSepareItemStateChanged

    private void btnRegistrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistrarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        tk.beep();
        
        int response =JOptionPane.showConfirmDialog(this, "¿Desea registrar la operación actual?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            if (chkSepare.isSelected()){
                //
                if(txtNombre.getText().isEmpty()||txtApellido.getText().isEmpty()||txtAbono.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Error, ingrese los campos abono, nombre y apellido\nopcionalmente puede agregar el número de teléfono", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    String tel;
                    String vi1=txtAbono.getText();
                    vi1=vi1.replaceAll("\\.", "");
                    int abono=Integer.parseInt(vi1);
                    if(txtTel.getText().isEmpty()){
                        op.insertar("separe", "id_factura, nombre, abono, id_local", idFactura+",'"+txtNombre.getText()+" "+txtApellido.getText()+"',"+abono+","+superLocalID, con);
                    }
                    else{
                        tel=txtTel.getText();
                        op.insertar("separe", "id_factura, nombre, telefono, abono, id_local", idFactura+",'"+txtNombre.getText()+" "+txtApellido.getText()+"','"+tel+"',"+abono+","+superLocalID, con);
                    }
                    //
                    
                    limpiar();
                    actualizar();
                    lblEstado.setText("¡Anterior factura de plan separe guardada con exito!");
                    lblEstado.setForeground(Color.blue);
                    //calculo menu ppal
                    String totPpal=txtTotal.getText();
                    totPpal=totPpal.replaceAll("\\.", "");
                }
            }
            else{
                limpiar();
                actualizar();
                lblEstado.setText("¡Anterior factura guardada con exito!");
                lblEstado.setForeground(Color.blue);  
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
       calcular();
    }//GEN-LAST:event_btnCalcularActionPerformed
    
    private void calcular(){
        try{
            String vi1=txtTotal.getText();
            vi1=vi1.replaceAll("\\.", "");
            int vi=Integer.parseInt(vi1);
            String paga=txtPaga.getText();
            paga=paga.replaceAll("\\.", "");
            int pagaT=Integer.parseInt(paga);
            System.out.println("Paga: "+pagaT+"Total: "+vi);
            if (pagaT<vi){
                lblEstado.setText("El valor ingresado es menor al total a pagar");
                lblEstado.setForeground(Color.red);
            }
            else
            {
                String vuelto=String.valueOf(pagaT-vi);
                txtVD.setText(vuelto);
                txtVD.requestFocus();//*machetazo para auto--recalcular
                txtTotal.requestFocus();//
                txtPaga.requestFocus();//*  
                lblEstado.setText("Total calculado");
                lblEstado.setForeground(Color.blue);
            }
        }
        catch(Exception ex){
            System.out.println(ex);
            lblEstado.setText("Error, ingrese sólo valores numéricos");
            lblEstado.setForeground(Color.red);
        }
    }
    private void txtPagaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPagaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagaFocusLost

    private void txtAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
            System.out.println("Caracter invalido");
            lblEstado.setText("ERROR: ingrese un caracter valido (solo numeros)");
            lblEstado.setForeground(Color.red);
        }
        else{
            lblEstado.setText("En espera");
            lblEstado.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtAbonoKeyTyped

    private void txtPagaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagaKeyTyped

    }//GEN-LAST:event_txtPagaKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
            System.out.println("Caracter invalido");
            lblEstado.setText("ERROR: ingrese un caracter valido (solo numeros)");
            lblEstado.setForeground(Color.red);
        }
        else{
            lblEstado.setText("En espera");
            lblEstado.setForeground(Color.blue);
        }
    }//GEN-LAST:event_txtTelKeyTyped

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        actualizar();
    }//GEN-LAST:event_formComponentShown

    private void lblTotalDebeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTotalDebeMouseClicked
        // TODO add your handling code here:
        egg++;
        if (egg>=5){
            egg=0;
            JOptionPane.showConfirmDialog(null, "¿Desea formatear su equipo?", ":V",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        }
    }//GEN-LAST:event_lblTotalDebeMouseClicked

    private void tablaDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDetalleMouseClicked

    private void txtPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagaActionPerformed
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_txtPagaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        tk.beep();
        int response =JOptionPane.showConfirmDialog(this, "¿Desea cancelar la operación actual?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            op.eliminar("detalle", "id_factura= "+idFactura, con);
            op.eliminar("factura", "id_factura= "+idFactura, con);
            //
            Iterator itr = prodOrig.iterator();
            while(itr.hasNext()){
                producto sel= (producto) (Object) itr.next();
                int idProd = Integer.parseInt(sel.getId());
                int exisRetiradas= Integer.parseInt(sel.getExistencias());
                Object[][] dtUser;
                dtUser = op.select("productos", "existencias", "id_producto="+idProd, con);
                String exisActuales=dtUser[0][0].toString();
                int agregar=Integer.parseInt(exisActuales)+exisRetiradas;
                System.out.println("ID "+ idProd+" Existencias actuales "+exisActuales+"Existencias retiradas: "+exisRetiradas+"\nSuma= "+agregar);
                op.modificar("productos", "existencias ="+agregar, "id_producto=" + idProd, con);
            }
            limpiar();
            actualizar();
            lblEstado.setText("¡Anterior factura cancelada!");
            lblEstado.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lblEstadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblEstadoPropertyChange
        // TODO add your handling code here:
        
        /*/lblEstado.setText("En espera");
        lblEstado.setForeground(Color.blue);/*/
    }//GEN-LAST:event_lblEstadoPropertyChange

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinner1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1PropertyChange

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1KeyPressed
    
    private void limpiar(){
        //variables********************
        bloqueadas.remove(jTabbedPane1.getSelectedComponent());
        egg=0;
        registrado=0;
        idFactura=0;
        fila=0;
        celda.clear();
        prodOrig.clear();
        eliminados.clear();
        //txt's y labels***************
        txtPaga.setEnabled(false);
        txtPaga.setText("");
        txtID.setText("");
        txtFecha.setText("");
        txtTel.setVisible(false);
        txtTel.setText("");
        lblTel.setVisible(false);
        //
        txtNombre.setVisible(false);
        txtNombre.setText("");
        lblNombre.setVisible(false);
        //
        txtApellido.setVisible(false);
        txtApellido.setText("");
        lblApellido.setVisible(false);
        //
        txtFFin.setVisible(false);
        txtFFin.setText("");
        lblFFin.setVisible(false);
        //
        txtAbono.setVisible(false);
        txtAbono.setText("");
        lblAbono.setVisible(false);
        //
        lblTotalDebe.setText("TOTAL");
        txtTotal.setText("");
        txtPaga.setText("");
        txtVD.setText("");
        //check************************
        chkSepare.setSelected(false);
        //botones**********************
        btnAgregar.setEnabled(false);
        lblCantidad.setEnabled(false);
        jSpinner1.setEnabled(false);
        btnCalcular.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnRegistrar.setEnabled(false);
        //tabla
        tablaDetalle.setModel(new DefaultTableModel());
        //spinner
        jSpinner1.setValue(1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox chkSepare;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblAbono;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFFin;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTotalDebe;
    private javax.swing.JList<String> prodList;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JFormattedTextField txtAbono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JFormattedTextField txtFFin;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtPaga;
    private javax.swing.JTextField txtTel;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JFormattedTextField txtVD;
    // End of variables declaration//GEN-END:variables

   
}
